# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/you/albums' do
  # This should return the minimal set of attributes required to create a valid
  # Album. As you add validations to Album, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Album.create! valid_attributes
      get you_albums_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      release = Album.create! valid_attributes
      get you_album_url(release)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_you_album_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      release = Album.create! valid_attributes
      get edit_you_album_url(release)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Album' do
        expect do
          post you_albums_url, params: { album: valid_attributes }
        end.to change(Album, :count).by(1)
      end

      it 'redirects to the created release' do
        post you_albums_url, params: { album: valid_attributes }
        expect(response).to redirect_to(you_album_url(Album.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Album' do
        expect do
          post you_albums_url, params: { album: invalid_attributes }
        end.not_to change(Album, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post you_albums_url, params: { album: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested release' do
        release = Album.create! valid_attributes
        patch you_album_url(release), params: { album: new_attributes }
        release.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the release' do
        release = Album.create! valid_attributes
        patch you_album_url(release), params: { album: new_attributes }
        release.reload
        expect(response).to redirect_to(you_album_url(release))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        release = Album.create! valid_attributes
        patch you_album_url(release), params: { album: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested release' do
      release = Album.create! valid_attributes
      expect do
        delete you_album_url(release)
      end.to change(Album, :count).by(-1)
    end

    it 'redirects to the albums list' do
      release = Album.create! valid_attributes
      delete you_album_url(release)
      expect(response).to redirect_to(you_albums_url)
    end
  end
end
